# seedserver Docker-Compose file
# variables are stored in .ENV
#
# Containers:
# [port:     ] watchtower: https://hub.docker.com/r/v2tec/watchtower
# [port:   80] heimdall: []https://hub.docker.com/r/linuxserver/heimdall
# [port: 9000] portainer:  https://hub.docker.com/r/portainer/portainer/
# [port: 9001] transmission VPN: https://hub.docker.com/r/haugene/transmission-openvpn
# [port: 9002] jackett: https://hub.docker.com/r/linuxserver/jackett
# [port: 9003] radarr: https://hub.docker.com/r/linuxserver/radarr
# [port: 9004] sonarr: https://hub.docker.com/r/linuxserver/sonarr
# [port: 9005] bazarr: https://hub.docker.com/r/linuxserver/bazarr

version: "2.1"

services:
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: always
    command: --schedule "0 0 23 * * SUN " --cleanup
    environment:
      - tz=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_POINT}/app_data/heimdall:/config

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_POINT}/app_data/portainer:/data

  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: always
    cap_add:
      - NET_ADMIN
    dns:
      - 1.1.1.1
      - 1.0.0.1
    ports:
      - "9001:9091"
      - "8888:8888"
      - "51413:51413"
    environment:
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - CREATE_TUN_DEVICE=true
      - LOCAL_NETWORK=192.168.0.0/24
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - TRANSMISSION_RPC_HOST_WHITELIST="127.0.0.1,192.168.*.*"
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_USERNAME}
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_PASSWORD}
      - TRANSMISSION_UMASK=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_DOWNLOAD_DIR=/downloads
      - TRANSMISSION_INCOMPLETE_DIR=/incomplete
      - WEBPROXY_ENABLED=true
      - WEBPROXY_PORT=8888
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_POINT}/app_data/transmission:/data
      - ${MOUNT_POINT}/app_data/downloads/completed:/downloads
      - ${MOUNT_POINT}/app_data/downloads/incomplete:/incomplete
  
  jackett:
    image: "linuxserver/jackett"
    container_name: jackett
    restart: always
    ports:
      - "9002:9117"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - RUN_OPTS=ProxyConnection=${HOST}:8888 # comment out this line to disable routing jackett through the OpenVPN proxy [transmission-openvpn]
    volumes:
      - ${CONFIG_POINT}/app_data/jackett:/config
      - ${CONFIG_POINT}/app_data/jackett:/data
  
  radarr:
    image: "linuxserver/radarr"
    container_name: radarr
    restart: always
    ports:
      - "9003:7878"
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=0
    volumes:
      - ${CONFIG_POINT}/app_data/radarr:/config
      - ${MOUNT_POINT}/app_data/downloads/completed:/downloads
      - ${MOUNT_POINT}/movies:/movies
  
  sonarr:
    image: "linuxserver/sonarr"
    container_name: sonarr
    restart: always
    ports:
      - "9004:8989"
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=0
    volumes:
      - ${CONFIG_POINT}/app_data/sonarr:/config
      - ${MOUNT_POINT}/app_data/downloads/completed:/downloads
      - ${MOUNT_POINT}/tv:/tv

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    restart: always
    ports:
      - 9005:6767
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=0
    volumes:
      - ${CONFIG_POINT}/app_data/bazarr:/config
      - ${MOUNT_POINT}/movies:/movies
      - ${MOUNT_POINT}/tv:/tv